//
//  CurrencyCode.swift
//  ByJo
//

import Foundation

enum CurrencyCode: String, CaseIterable, Codable {
    case usd = "USD"
    case eur = "EUR"
    case gbp = "GBP"
    case jpy = "JPY"
    case cad = "CAD"
    case aud = "AUD"
    case chf = "CHF"
    case cny = "CNY"
    case inr = "INR"
    case rub = "RUB"
    case brl = "BRL"
    case zar = "ZAR"
    case mxn = "MXN"
    case krw = "KRW"
    case sek = "SEK"
    case nok = "NOK"
    case dkk = "DKK"
    case hkd = "HKD"
    case sgd = "SGD"
    case nzd = "NZD"
    case thb = "THB"
    case tryy = "TRY"
    case myr = "MYR"
    case idr = "IDR"
    case php = "PHP"
    case pln = "PLN"
    case huf = "HUF"
    case czk = "CZK"
    case ils = "ILS"
    case aed = "AED"
    case sar = "SAR"
    case kwd = "KWD"
    case bdt = "BDT"
    case lkr = "LKR"
    case vnd = "VND"
    case egp = "EGP"
    case ngn = "NGN"
    case ars = "ARS"
    case clp = "CLP"
    case pkr = "PKR"
    case ron = "RON"
    case uah = "UAH"
    case bgn = "BGN"
    case hrk = "HRK"
    case rsd = "RSD"
    case isk = "ISK"
    case jod = "JOD"
    case omr = "OMR"
    case qar = "QAR"
    case mvr = "MVR"

    var symbol: String {
        switch self {
        case .usd: return "$"
        case .eur: return "€"
        case .gbp: return "£"
        case .jpy, .cny: return "¥"
        case .cad: return "CA$"
        case .aud: return "A$"
        case .chf: return "CHF"
        case .inr: return "₹"
        case .rub: return "₽"
        case .brl: return "R$"
        case .zar: return "R"
        case .mxn: return "Mex$"
        case .krw: return "₩"
        case .sek, .nok, .dkk, .isk: return "kr"
        case .hkd: return "HK$"
        case .sgd: return "S$"
        case .nzd: return "NZ$"
        case .thb: return "฿"
        case .tryy: return "₺"
        case .myr: return "RM"
        case .idr: return "Rp"
        case .php: return "₱"
        case .pln: return "zł"
        case .huf: return "Ft"
        case .czk: return "Kč"
        case .ils: return "₪"
        case .aed: return "د.إ"
        case .sar: return "﷼"
        case .kwd: return "د.ك"
        case .bdt: return "৳"
        case .lkr: return "රු"
        case .vnd: return "₫"
        case .egp: return "£"
        case .ngn: return "₦"
        case .ars: return "$"
        case .clp: return "$"
        case .pkr: return "₨"
        case .ron: return "lei"
        case .uah: return "₴"
        case .bgn: return "лв"
        case .hrk: return "kn"
        case .rsd: return "дин"
        case .jod: return "د.ا"
        case .omr, .qar: return "﷼"
        case .mvr: return "Rf"
        }
    }
}
